#!/bin/bash

SMTPFROM=user@gmail.com
SMTPTO=user@hotmail.com
SMTPSERVER=smtp.googlemail.com:587
SMTPUSER=username
SMTPPASSWORD=PASSWORD
SUBJECT="SMTP protocol test"

df -h | grep Filesystem > /tmp/discusage.txt
df -h | grep sda5 >> /tmp/discusage.txt

sendEmail -f $SMTPFROM -t $SMTPTO -s $SMTPSERVER -u $SUBJECT  -xu $SMTPUSER -xp $SMTPPASSWORD -o tls=yes -o message-file=/tmp/discusage.txt

rm /tmp/discusage.txt
